# Generated by Django 4.2.5 on 2023-11-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoTice',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('mag', models.TextField(max_length=500)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
