# Generated by Django 4.2.5 on 2023-11-06 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='mag',
            new_name='msg',
        ),
    ]
