# Generated by Django 4.2.5 on 2023-11-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_rename_mag_notice_msg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoTice',
            new_name='Nmgmt',
        ),
    ]
