# Generated by Django 4.2.5 on 2023-10-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=255)),
                ('idno', models.CharField(max_length=15)),
                ('rnumber', models.CharField(max_length=15)),
            ],
        ),
    ]
