# Generated by Django 4.2.5 on 2023-10-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_form_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='pidimg',
            field=models.FileField(null=True, upload_to='static/img/id'),
        ),
    ]
