# Generated by Django 4.2.5 on 2023-10-27 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_form_pidimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='pidimg',
            new_name='idimg',
        ),
    ]
