# Generated by Django 4.2.5 on 2023-10-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_form_idimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='idimg',
            field=models.FileField(max_length=250, null=True, upload_to='image/'),
        ),
    ]
