# Generated by Django 4.2.5 on 2023-10-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_alter_form_idimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompLain',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=15)),
                ('complain', models.TextField(max_length=255)),
            ],
        ),
    ]
