# Generated by Django 4.2.5 on 2023-10-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_complain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='complain',
        ),
        migrations.AddField(
            model_name='complain',
            name='scomplain',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
