# Generated by Django 4.2.5 on 2023-10-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_complainraised_delete_complain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complainraised',
            old_name='name',
            new_name='sname',
        ),
        migrations.AlterField(
            model_name='complainraised',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='complainraised',
            name='year',
            field=models.CharField(max_length=15),
        ),
    ]
