# Generated by Django 4.2.5 on 2023-10-31 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_rename_name_complainraised_sname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComplainRaised',
        ),
    ]
