# Generated by Django 4.2.5 on 2023-11-06 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_studentp_alter_form_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='sno',
            field=models.AutoField(db_column='id_text', default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
