# Generated by Django 4.2.6 on 2023-11-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_alter_form_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='idimg',
        ),
    ]
